# -*- coding: utf-8 -*-
"""sqm_strategy.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Irop_cvcdH2FiPe9jpGJvyXB74_TxXW6
"""

import pandas as pd
import numpy as np
import FinanceDataReader as fdr
import warnings

warnings.filterwarnings('ignore')

def check_macro_circuit_breaker(price_index):

    # KOSPI 지수 호출
    kospi_real = fdr.DataReader('KS11')
    kospi_close = kospi_real['Close'].reindex(price_index, method='ffill')

    # 거시 지표 연산
    mkt_daily_ret = kospi_close.pct_change(fill_method=None)
    mkt_5d_ret = kospi_close.pct_change(5)
    mkt_vol_20d = mkt_daily_ret.rolling(20).std() * np.sqrt(252)

    t = price_index[-1]
    recent_5d_drop = mkt_5d_ret.loc[t]
    current_mkt_vol = mkt_vol_20d.loc[t]

    VOL_LIMIT = 0.25
    is_panic = (recent_5d_drop < -0.05) or ((current_mkt_vol > VOL_LIMIT) and (recent_5d_drop < 0))

    return is_panic, recent_5d_drop, current_mkt_vol

def generate_sqm_portfolio(price_df, volume_df, marcap_df, sector_map, current_holdings=None):
    """
    핵심 알파 엔진: 가격, 거래대금, 시가총액, 섹터 데이터를 주입받아 최종 포트폴리오를 산출

    """
    if current_holdings is None:
        current_holdings = []

    t = price_df.index[-1]

    # 1. 서킷 브레이커 확인
    is_panic, recent_5d_drop, current_mkt_vol = check_macro_circuit_breaker(price_df.index)

    print(f"\n 기준일: {t.strftime('%Y-%m-%d')}")
    print("-" * 70)
    print(f" [거시 위험(Tail-Risk) 진단]")
    print(f" - 최근 5일 지수 수익률: {recent_5d_drop*100:.2f}% (Panic: < -5.00%)")
    print(f" - KOSPI 20일 변동성: {current_mkt_vol*100:.2f}% (Panic: > 25.00% & 하락장)")
    print("-" * 70)

    if is_panic:
        print(" [서킷 브레이커 발동] 꼬리 위험(Tail-Risk) 구간 진입.")
        print(" 전량 매도 후 100% 현금(Cash)을 보유하여 포트폴리오를 방어합니다.")
        return pd.DataFrame() # 빈 포트폴리오(현금 100%) 반환

    print(" [안전 구간 확인] 서킷 브레이커 해제. 주도주 스캐닝을 시작합니다.")

    # 2. 알파 지표(Smooth MOM) 계산
    mom_60d = price_df.pct_change(60)
    price_diff_abs = price_df.diff(1).abs()
    path_distance_60d = price_diff_abs.rolling(60).sum()
    net_price_change = price_df.diff(60).abs()

    efficiency_ratio = net_price_change / path_distance_60d
    smooth_mom_score = mom_60d * efficiency_ratio
    vol_5_df = volume_df.rolling(5).mean()

    # 3. 당일 데이터 스냅샷
    mc = marcap_df.loc[t]
    v_5 = vol_5_df.loc[t]
    raw_mom = mom_60d.loc[t]
    smooth_mom = smooth_mom_score.loc[t]

    # 4. 유니버스 필터링 (시총 5천억, 거래대금 50억)
    mask = (mc >= 500_000) & (v_5 >= 5_000_000_000) & raw_mom.notna() & smooth_mom.notna()
    valid_tickers = mask[mask].index

    df_t = pd.DataFrame({'Raw_MOM': raw_mom, 'Smooth_MOM': smooth_mom, 'MarketCap': mc}).loc[valid_tickers]
    df_t['Sector'] = df_t.index.map(sector_map)
    df_t = df_t.dropna(subset=['Sector'])

    # 5. Top-Down 주도 섹터 산출
    df_t['Weighted_MOM'] = df_t['Raw_MOM'] * df_t['MarketCap']
    sector_mom = df_t.groupby('Sector')['Weighted_MOM'].sum() / df_t.groupby('Sector')['MarketCap'].sum()
    top_3_sectors = sector_mom.nlargest(3).index.tolist()
    df_t['Is_Top_Sector'] = df_t['Sector'].isin(top_3_sectors)

    # 섹터별 비중 상한(CAP)
    total_mcap = df_t['MarketCap'].sum()
    sector_mkt_wt = df_t.groupby('Sector')['MarketCap'].sum() / total_mcap
    sector_max_wt = np.maximum(2 * sector_mkt_wt, 0.10)
    sector_allocated = {s: 0.0 for s in sector_max_wt.index}

    # 6. Bottom-Up 스코어링 정렬
    ranked = df_t.sort_values(by=['Is_Top_Sector', 'Smooth_MOM'], ascending=[False, False])
    ranked_tickers = ranked.index.tolist()

    # 7. Buffer Rule 적용 및 15종목 선정
    selected_tickers = []
    top_30_tickers = ranked_tickers[:30]

    for ticker in current_holdings:
        if ticker in top_30_tickers:
            s = ranked.loc[ticker, 'Sector']
            if sector_allocated[s] + 0.066 <= sector_max_wt[s]:
                selected_tickers.append(ticker)
                sector_allocated[s] += 0.066

    for ticker in ranked_tickers:
        if len(selected_tickers) >= 15:
            break
        if ticker not in selected_tickers:
            s = ranked.loc[ticker, 'Sector']
            if sector_allocated[s] + 0.066 <= sector_max_wt[s]:
                selected_tickers.append(ticker)
                sector_allocated[s] += 0.066

    # 8. 동일 비중(1/N) 배분
    target_weights = {}
    current_weight_sum = 0.0
    sector_allocated = {s: 0.0 for s in sector_max_wt.index}

    for ticker in selected_tickers:
        if current_weight_sum >= 0.999:
            break
        s = ranked.loc[ticker, 'Sector']
        room_in_sector = sector_max_wt[s] - sector_allocated[s]
        if room_in_sector <= 0.001:
            continue

        target_alloc = 1.0 / 15.0
        alloc = min(target_alloc, 0.15, room_in_sector, 1.0 - current_weight_sum)

        if alloc > 0:
            target_weights[ticker] = alloc
            sector_allocated[s] += alloc
            current_weight_sum += alloc

    # 9. KRX 종목명 매핑
    krx_df = fdr.StockListing('KRX')
    name_dict = {str(row['Code']): row['Name'] for _, row in krx_df.iterrows()}
    name_dict.update({'A' + str(row['Code']): row['Name'] for _, row in krx_df.iterrows()})

    # 최종 결과 포맷팅
    final_portfolio = pd.DataFrame({
        '종목코드': list(target_weights.keys()),
        '종목명': [name_dict.get(str(tk), '알수없음') for tk in target_weights.keys()],
        '섹터명': [ranked.loc[tk, 'Sector'] for tk in target_weights.keys()],
        'Smooth_MOM_Score': [ranked.loc[tk, 'Smooth_MOM'] for tk in target_weights.keys()],
        '투자 비중(%)': [target_weights[tk] * 100 for tk in target_weights.keys()]
    })
    final_portfolio.index = np.arange(1, len(final_portfolio) + 1)

    print("\n[최종 편입 포트폴리오 (1/N 동일가중)]")
    print("-" * 75)
    print(final_portfolio.to_string(formatters={'Smooth_MOM_Score': '{:.4f}'.format, '투자 비중(%)': '{:.2f}%'.format}))
    print("-" * 75)
    print(f"총 편입 비중: {sum(target_weights.values()) * 100:.2f}%\n")

    return final_portfolio


if __name__ == "__main__":
    print(" 이 모듈은 데이터프레임(가격, 거래대금, 시총)을 주입받아 작동하는 전략 엔진입니다.")
    print("사용법: portfolio = generate_sqm_portfolio(price_df, volume_df, marcap_df, sector_dict)")